"""Continuous preview arms for the ForestGirl two-handed tool pose.

The supplied character uses separately capped, rigid sleeve/cuff/arm pieces.
Those pieces open at bent elbows and at independently oriented grip wrists.
This replacement keeps their low-poly silhouette and materials while sharing
the ring vertices across each joint. It only affects the isolated hoe preview.
"""
import math
import bpy
from mathutils import Matrix, Vector


def _smooth(value):
    value = max(0.0, min(1.0, value))
    return value * value * (3.0 - 2.0 * value)


def repair_arms(rig, arm_length_scale=1.0):
    """Replace rigid arm pieces with connected, blended sleeves and wrists.

    Call in the rest pose, after removing source hands and before grip_hands.
    A fixed arm_length_scale adjusts both arm rest segments about the shoulder;
    there is no animated stretch. New geometry is in armature local coordinates.
    The final ring overlaps the replacement palm generated by grip_hands.
    Returns a small serializable geometry/rest-proportion validation report.
    """
    if not 1.0 <= arm_length_scale <= 1.5:
        raise ValueError('Preview arm length scale must be between 1.0 and 1.5')
    if any(p.matrix_basis != Matrix.Identity(4) for p in rig.pose.bones):
        raise ValueError('repair_arms requires the character rest pose')
    source = {}
    rest = {}
    for side in ('L', 'R'):
        names = ['Jacket • '+side+' shoulder', 'Jacket • '+side+' sleeve',
                 'Jacket • '+side+' sleeve piping', 'Linen • '+side+' cuff',
                 'Linen • '+side+' rolled cuff edge', 'Arm • '+side]
        objects = [bpy.data.objects.get(name) for name in names]
        if any(ob is None for ob in objects):
            raise ValueError('Source ForestGirl arm parts not found: '+side)
        source[side] = objects
        upper, lower, hand = (rig.data.bones[name+'.'+side]
                              for name in ('upper_arm', 'forearm', 'hand'))
        rest[side] = (upper.head_local.copy(), upper.tail_local.copy(),
                      lower.tail_local.copy(), hand.tail_local-hand.head_local)

    # Editing all three joints together preserves the skeleton's connected
    # endpoints; all affected source arm meshes are replaced below.
    bpy.ops.object.select_all(action='DESELECT')
    rig.select_set(True)
    bpy.context.view_layer.objects.active = rig
    bpy.ops.object.mode_set(mode='EDIT')
    for side, (shoulder, elbow, wrist, hand_vector) in rest.items():
        elbow = shoulder + (elbow-shoulder)*arm_length_scale
        wrist = shoulder + (wrist-shoulder)*arm_length_scale
        upper, lower, hand = (rig.data.edit_bones[name+'.'+side]
                             for name in ('upper_arm', 'forearm', 'hand'))
        upper.tail = elbow
        lower.head = elbow
        lower.tail = wrist
        hand.head = wrist
        hand.tail = wrist+hand_vector
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.context.view_layer.update()

    scale = rig.matrix_world.to_scale().x
    report = {'arm_length_scale':arm_length_scale, 'continuous_arm_meshes':[],
              'arm_segment_total_length_m':{}, 'elbow_shared_ring_vertices':10,
              'wrist_shared_ring_vertices':10}
    for side in ('L', 'R'):
        sign = -1 if side == 'L' else 1
        objects = source[side]
        materials = [objects[i].data.materials[0] for i in (1,2,3,4,5)]
        upper, lower, hand = (rig.data.bones[name+'.'+side]
                             for name in ('upper_arm', 'forearm', 'hand'))
        shoulder, elbow, wrist = upper.head_local, upper.tail_local, lower.tail_local
        updir = (elbow-shoulder).normalized()
        lowdir = (wrist-elbow).normalized()
        # (center, radius in source units, lower-weight, material index).
        # Two close rings across the rolled cuff form its annular lip; skin
        # remains part of the same surface instead of a detached capped cone.
        stations = [
            (shoulder-updir*.020,.128,0.0,0),
            (shoulder+(elbow-shoulder)*.15,.158,0.0,0),
            (shoulder+(elbow-shoulder)*.42,.185,0.0,0),
            (shoulder+(elbow-shoulder)*.76,.173,0.0,0),
            (shoulder+(elbow-shoulder)*.88,.165,.12,1),
            (elbow,.157,.50,2),
            (elbow+(wrist-elbow)*.12,.152,.88,2),
            (elbow+(wrist-elbow)*.28,.151,1.0,2),
            (elbow+(wrist-elbow)*.53,.155,1.0,3),
            (elbow+(wrist-elbow)*.61,.156,1.0,3),
            (elbow+(wrist-elbow)*.64,.094,1.0,4),
            (elbow+(wrist-elbow)*.80,.087,1.0,4),
            (elbow+(wrist-elbow)*.94,.079,1.0,4),
            (wrist,.076,1.0,4),
        ]
        vertices, weights = [], []
        for row, (center, radius, lower_weight, _) in enumerate(stations):
            tangent = (updir if row<4 else lowdir if row>6 else
                       (updir+lowdir).normalized())
            normal = tangent.cross(Vector((0,1,0))).normalized()
            other = tangent.cross(normal).normalized()
            # Blend wrist skin toward the hand's orientation over its final
            # 25 mm. The palm base is fully hand-weighted, so its seam cannot
            # open when the independently posed hand rolls on the shaft.
            hand_weight = _smooth((row-11)/3) if row>=11 else 0
            for column in range(10):
                angle = math.tau*column/10
                point = center+radius*(math.cos(angle)*normal+math.sin(angle)*other)
                if row == len(stations)-1:
                    # Same ring order and palm cross-section at both ends of
                    # the hand-owned strip prevents a 90-degree terminal twist.
                    point = hand.matrix_local @ (Vector((.021*math.cos(angle),
                                                          .021*math.sin(angle),0))/scale)
                vertices.append(tuple(point))
                weights.append({'upper_arm.'+side:(1-lower_weight)*(1-hand_weight),
                                'forearm.'+side:lower_weight*(1-hand_weight),
                                'hand.'+side:hand_weight})
        # The existing preview palm has center (-sign*10, 2, -6) mm
        # relative to its wrist in tool/hand coordinates, not along the rest
        # forearm. Rebind the terminal ring in that same basis and overlap it.
        palm_center = Vector((-sign*.010,.002,-.006))/scale
        for column in range(10):
            angle = math.tau*column/10
            palm_offset = Vector((.0135*math.cos(angle),.0175*math.sin(angle),0))/scale
            vertices.append(tuple(hand.matrix_local@(palm_center+palm_offset)))
            weights.append({'hand.'+side:1.0})
        count = len(stations)+1
        faces = [tuple(reversed(range(10)))]
        face_materials = [0]
        for row in range(count-1):
            mat = stations[min(row,len(stations)-1)][3]
            for column in range(10):
                a=row*10+column; b=row*10+(column+1)%10
                faces.append((a,b,b+10,a+10))
                face_materials.append(mat)
        faces.append(tuple((count-1)*10+column for column in range(10)))
        face_materials.append(4)
        data=bpy.data.meshes.new('HoeArm_'+side+'_Continuous')
        data.from_pydata(vertices,[],faces);data.update()
        ob=bpy.data.objects.new('HoeArm_'+side+'_Continuous',data)
        bpy.context.scene.collection.objects.link(ob)
        ob.parent=rig;ob.matrix_parent_inverse=Matrix.Identity(4);ob.matrix_basis=Matrix.Identity(4)
        for mat in materials:data.materials.append(mat)
        for face,mat in zip(data.polygons,face_materials):face.material_index=mat
        for bone in ('upper_arm.'+side,'forearm.'+side,'hand.'+side):
            group=ob.vertex_groups.new(name=bone)
            for index,values in enumerate(weights):
                if values.get(bone,0)>0:group.add([index],values[bone],'REPLACE')
        mod=ob.modifiers.new('Continuous elbow and wrist skinning','ARMATURE');mod.object=rig
        for old in objects:bpy.data.objects.remove(old,do_unlink=True)
        # Closed strip, with no separate open boundary at either joint.
        edge_counts={}
        for face in faces:
            for a,b in zip(face,face[1:]+face[:1]):
                key=tuple(sorted((a,b)));edge_counts[key]=edge_counts.get(key,0)+1
        assert all(count==2 for count in edge_counts.values()), 'Arm surface must be closed'
        assert all(abs(sum(values.values())-1)<1e-7 for values in weights)
        report['continuous_arm_meshes'].append(ob.name)
        report['arm_segment_total_length_m'][side]=(upper.length+lower.length)*scale
    return report
